import type { KnowledgeGraphLayerCapabilities } from './knowledge-graph-layer.interface';

export const KNOWLEDGE_GRAPH_LAYER_CAPABILITIES: KnowledgeGraphLayerCapabilities = {
  nodeTypes: [
    'CASE',
    'COMPLAINANT',
    'VICTIM',
    'ACCUSED',
    'WITNESS',
    'OFFICER',
    'UNIT',
    'DISTRICT',
    'STATE',
    'COURT',
    'ACT',
    'SECTION',
    'CRIME_HEAD',
    'CRIME_SUB_HEAD',
    'OCCURRENCE',
    'EVIDENCE',
    'VEHICLE',
    'PHONE_DIGITAL_IDENTIFIER',
    'FINANCIAL_ACCOUNT',
    'FINANCIAL_TRANSACTION',
    'WEAPON',
    'FORENSIC_REPORT',
    'HOTSPOT',
    'CRIME_STATISTIC',
    'CRIME_REVIEW_REPORT',
    'REPORT_SECTION',
    'GANG_NETWORK',
    'REPEAT_OFFENDER_PROFILE',
    'MODUS_OPERANDI',
    'SOCIAL_RELATIONSHIP',
    'ADDRESS_HISTORY',
    'ORGANIZATION',
    'RISK_SCORE',
    'RECOMMENDATION',
    'CASE_SIMILARITY',
    'ALERT',
    'TASK',
    'CHAT_SESSION',
    'CHAT_MESSAGE',
    'SEARCH_REQUEST',
    'DATA_SOURCE',
    'DATA_QUALITY_ISSUE',
    'DOCUMENT_ATTACHMENT',
    'MODEL_AUDIT_LOG',
    'FEATURE_VECTOR',
  ],
  supportsTraversal: true,
  supportsShortestPath: true,
  supportsKHopSearch: true,
  supportsCommunityDetection: true,
  supportsCentrality: true,
  supportsRelationshipExpansion: true,
  supportsSummarization: true,
  supportsExplanation: true,
  supportedAlgorithms: [
    'shortest_path',
    'k_hop_search',
    'community_detection',
    'centrality',
    'connected_components',
    'relationship_expansion',
    'graph_summarization',
    'graph_explanation',
  ],
};
