import { ROLES } from '@core/auth/roles';
import { PERMISSIONS } from '@core/auth/permissions';
import type {
  AnalyticsAgentContract,
  GraphAgentContract,
  InvestigationAgentContract,
  LegalAgentContract,
  RecommendationAgentContract,
  ReportAgentContract,
  SupervisorAgentContract,
} from './domain-agents.interface';

export const investigationAgentContract: InvestigationAgentContract = {
  name: 'investigation',
  displayName: 'Investigation Agent',
  description: 'Handles case understanding, timeline construction, similar-case discovery, and lead-oriented investigation support.',
  responsibilities: ['case_summary', 'case_timeline', 'similar_case_search', 'investigation_lead_generation', 'victim_pattern_analysis'],
  input: {
    description: 'Accepts case-centric requests, structured case references, and investigator questions.',
    requiredFields: ['query'],
    optionalFields: ['caseMasterId', 'crimeNo', 'victimName', 'accusedName', 'requestedView'],
    acceptsCaseContext: true,
    acceptsConversationContext: true,
    acceptsStructuredEntities: true,
    acceptsUserQuery: true,
    shape: {},
  },
  output: {
    description: 'Produces investigation-oriented summaries, timelines, similar cases, and suggested leads.',
    primaryPayload: 'investigation insights',
    includesEvidence: true,
    includesConfidence: true,
    includesWarnings: true,
    includesHumanReviewFlag: true,
    shape: {},
  },
  tools: ['searchCase', 'searchVictim', 'searchAccused', 'searchOfficer', 'findSimilarCases', 'generateTimeline', 'generateSummary'],
  memory: {
    scope: 'investigation',
    description: 'Retains active case context and referenced persons across a focused investigation session.',
    retainedFields: ['caseMasterId', 'crimeNo', 'referencedVictimIds', 'referencedAccusedIds', 'recentQueries'],
    redactedFields: ['fullNarrativeRaw'],
    ttlSeconds: 3600,
  },
  prompt: {
    mode: 'required',
    promptKey: 'investigation.agent.system',
    promptVersionRequired: true,
    allowRuntimeOverride: false,
    notes: ['Prompt content is deferred to a later phase.', 'Agent must stay evidence-backed and non-speculative.'],
  },
  failureHandling: {
    mode: 'degrade_gracefully',
    retryableErrorCodes: ['AI_TOOL_TIMEOUT', 'AI_PROVIDER_TIMEOUT'],
    fallbackActions: ['return_partial_evidence', 'mark_missing_context', 'request_human_review'],
    escalateToHumanReview: true,
    suppressUnsupportedClaims: true,
  },
  confidence: {
    mode: 'required',
    minimumEvidenceCount: 1,
    requiresSourceAttribution: true,
    requiresScoreBreakdown: true,
    downgradeOnMissingEvidence: true,
  },
  evidence: {
    mode: 'required',
    minimumCitationCount: 1,
    requireStructuredSources: true,
    requireConflictingEvidenceWarnings: true,
    allowedSourceTypes: ['CASE', 'VICTIM', 'ACCUSED', 'OFFICER', 'CASE_SIMILARITY'],
  },
};

export const legalAgentContract: LegalAgentContract = {
  name: 'legal',
  displayName: 'Legal Agent',
  description: 'Handles legal act lookup, IPC/BNS section search, explanation, and section recommendation support.',
  responsibilities: ['legal_section_lookup', 'legal_recommendation'],
  input: {
    description: 'Accepts case narratives, act and section lookups, and legal reasoning requests.',
    requiredFields: ['query'],
    optionalFields: ['caseMasterId', 'narrative', 'actCode', 'sectionCode', 'requestedView'],
    acceptsCaseContext: true,
    acceptsConversationContext: true,
    acceptsStructuredEntities: true,
    acceptsUserQuery: true,
    shape: {},
  },
  output: {
    description: 'Produces legal matches, legal explanations, and suggested sections with reasons.',
    primaryPayload: 'legal analysis',
    includesEvidence: true,
    includesConfidence: true,
    includesWarnings: true,
    includesHumanReviewFlag: true,
    shape: {},
  },
  tools: ['searchActs', 'searchIPC', 'recommendIPC', 'translate'],
  memory: {
    scope: 'session',
    description: 'Retains current legal discussion context and referenced acts/sections within a session.',
    retainedFields: ['referencedActCodes', 'referencedSectionCodes', 'recentLegalQuestions'],
    ttlSeconds: 1800,
  },
  prompt: {
    mode: 'required',
    promptKey: 'legal.agent.system',
    promptVersionRequired: true,
    allowRuntimeOverride: false,
    notes: ['Agent must not invent legal sections.', 'All legal claims must map to structured legal sources.'],
  },
  failureHandling: {
    mode: 'fallback_to_supervisor_review',
    retryableErrorCodes: ['AI_TOOL_TIMEOUT'],
    fallbackActions: ['return_verified_matches_only', 'flag_manual_legal_review'],
    escalateToHumanReview: true,
    suppressUnsupportedClaims: true,
  },
  confidence: {
    mode: 'required',
    minimumEvidenceCount: 1,
    requiresSourceAttribution: true,
    requiresScoreBreakdown: true,
    downgradeOnMissingEvidence: true,
  },
  evidence: {
    mode: 'required',
    minimumCitationCount: 1,
    requireStructuredSources: true,
    requireConflictingEvidenceWarnings: true,
    allowedSourceTypes: ['ACT', 'IPC_SECTION', 'BNS_SECTION', 'LEGAL_KNOWLEDGE'],
  },
};

export const analyticsAgentContract: AnalyticsAgentContract = {
  name: 'analytics',
  displayName: 'Analytics Agent',
  description: 'Handles crime trends, forecasts, hotspot interpretation, and district or station performance insights.',
  responsibilities: ['crime_trend_analysis', 'crime_forecasting', 'hotspot_analysis'],
  input: {
    description: 'Accepts metric-driven analytic questions filtered by geography, time, or crime category.',
    requiredFields: ['query'],
    optionalFields: ['districtId', 'unitId', 'metric', 'crimeCategory', 'fromDate', 'toDate', 'requestedView'],
    acceptsCaseContext: false,
    acceptsConversationContext: true,
    acceptsStructuredEntities: true,
    acceptsUserQuery: true,
    shape: {},
  },
  output: {
    description: 'Produces analytic insights, trend summaries, forecasts, and hotspot-oriented findings.',
    primaryPayload: 'analytics insights',
    includesEvidence: true,
    includesConfidence: true,
    includesWarnings: true,
    includesHumanReviewFlag: false,
    shape: {},
  },
  tools: ['searchAnalytics', 'searchHotspots', 'generateSummary'],
  memory: {
    scope: 'session',
    description: 'Retains current filters and comparative analysis context across analytic follow-up questions.',
    retainedFields: ['districtId', 'unitId', 'metric', 'crimeCategory', 'timeWindow'],
    ttlSeconds: 1800,
  },
  prompt: {
    mode: 'optional',
    promptKey: 'analytics.agent.system',
    promptVersionRequired: true,
    allowRuntimeOverride: false,
    notes: ['Most analytics work should prefer deterministic summarization over freeform reasoning.'],
  },
  failureHandling: {
    mode: 'degrade_gracefully',
    retryableErrorCodes: ['AI_TOOL_TIMEOUT'],
    fallbackActions: ['return_partial_series', 'return_metric_unavailable_warning'],
    escalateToHumanReview: false,
    suppressUnsupportedClaims: true,
  },
  confidence: {
    mode: 'derived',
    minimumEvidenceCount: 1,
    requiresSourceAttribution: true,
    requiresScoreBreakdown: false,
    downgradeOnMissingEvidence: true,
  },
  evidence: {
    mode: 'required',
    minimumCitationCount: 1,
    requireStructuredSources: true,
    requireConflictingEvidenceWarnings: true,
    allowedSourceTypes: ['ANALYTICS', 'CRIME_REVIEW', 'HOTSPOT'],
  },
};

export const graphAgentContract: GraphAgentContract = {
  name: 'graph',
  displayName: 'Graph Agent',
  description: 'Handles graph traversal, relationship expansion, community clues, and network-centric investigation support.',
  responsibilities: ['relationship_expansion', 'network_analysis'],
  input: {
    description: 'Accepts entity-rooted graph exploration requests with optional depth and relationship filters.',
    requiredFields: ['query', 'rootEntityType', 'rootEntityId'],
    optionalFields: ['depth', 'requestedView'],
    acceptsCaseContext: true,
    acceptsConversationContext: true,
    acceptsStructuredEntities: true,
    acceptsUserQuery: true,
    shape: {},
  },
  output: {
    description: 'Produces connection summaries, network clues, and expanded related-entity views.',
    primaryPayload: 'graph insights',
    includesEvidence: true,
    includesConfidence: true,
    includesWarnings: true,
    includesHumanReviewFlag: true,
    shape: {},
  },
  tools: ['searchGraph', 'searchCase', 'searchAccused', 'searchVictim'],
  memory: {
    scope: 'case',
    description: 'Retains current root entity and graph traversal context for linked exploration.',
    retainedFields: ['rootEntityType', 'rootEntityId', 'lastTraversalDepth', 'relationshipFilters'],
    ttlSeconds: 2400,
  },
  prompt: {
    mode: 'optional',
    promptKey: 'graph.agent.system',
    promptVersionRequired: true,
    allowRuntimeOverride: false,
    notes: ['Graph interpretation must preserve raw edge meaning and confidence where available.'],
  },
  failureHandling: {
    mode: 'degrade_gracefully',
    retryableErrorCodes: ['AI_TOOL_TIMEOUT', 'AI_TOOL_DEPENDENCY_UNAVAILABLE'],
    fallbackActions: ['return_partial_network', 'mark_unexpanded_edges'],
    escalateToHumanReview: true,
    suppressUnsupportedClaims: true,
  },
  confidence: {
    mode: 'derived',
    minimumEvidenceCount: 1,
    requiresSourceAttribution: true,
    requiresScoreBreakdown: true,
    downgradeOnMissingEvidence: true,
  },
  evidence: {
    mode: 'required',
    minimumCitationCount: 1,
    requireStructuredSources: true,
    requireConflictingEvidenceWarnings: true,
    allowedSourceTypes: ['GRAPH_NODE', 'GRAPH_EDGE', 'CASE', 'PERSON', 'PHONE', 'VEHICLE'],
  },
};

export const recommendationAgentContract: RecommendationAgentContract = {
  name: 'recommendation',
  displayName: 'Recommendation Agent',
  description: 'Synthesizes investigation, legal, graph, and analytics signals into actionable next-step recommendations.',
  responsibilities: ['recommendation_generation', 'legal_recommendation', 'investigation_lead_generation'],
  input: {
    description: 'Accepts case narratives, case identifiers, and recommendation-type requests.',
    requiredFields: ['query'],
    optionalFields: ['caseMasterId', 'narrative', 'districtId', 'recommendationType'],
    acceptsCaseContext: true,
    acceptsConversationContext: true,
    acceptsStructuredEntities: true,
    acceptsUserQuery: true,
    shape: {},
  },
  output: {
    description: 'Produces actionable recommendations with reasons, priority, and missing-evidence flags.',
    primaryPayload: 'recommendation set',
    includesEvidence: true,
    includesConfidence: true,
    includesWarnings: true,
    includesHumanReviewFlag: true,
    shape: {},
  },
  tools: ['searchRecommendations', 'recommendIPC', 'findSimilarCases', 'searchGraph', 'searchAnalytics', 'searchHotspots'],
  memory: {
    scope: 'investigation',
    description: 'Retains the evolving recommendation context for an active case or briefing session.',
    retainedFields: ['caseMasterId', 'recommendationType', 'previousRecommendations', 'followUpQuestions'],
    ttlSeconds: 3600,
  },
  prompt: {
    mode: 'required',
    promptKey: 'recommendation.agent.system',
    promptVersionRequired: true,
    allowRuntimeOverride: false,
    notes: ['Recommendations must explain why, cite evidence, and avoid mandatory legal conclusions.'],
  },
  failureHandling: {
    mode: 'fallback_to_supervisor_review',
    retryableErrorCodes: ['AI_TOOL_TIMEOUT', 'AI_PROVIDER_TIMEOUT'],
    fallbackActions: ['return_verified_recommendations_only', 'flag_insufficient_evidence'],
    escalateToHumanReview: true,
    suppressUnsupportedClaims: true,
  },
  confidence: {
    mode: 'required',
    minimumEvidenceCount: 2,
    requiresSourceAttribution: true,
    requiresScoreBreakdown: true,
    downgradeOnMissingEvidence: true,
  },
  evidence: {
    mode: 'required',
    minimumCitationCount: 2,
    requireStructuredSources: true,
    requireConflictingEvidenceWarnings: true,
    allowedSourceTypes: ['RECOMMENDATION', 'CASE', 'IPC_SECTION', 'GRAPH_EDGE', 'ANALYTICS', 'HOTSPOT'],
  },
};

export const reportAgentContract: ReportAgentContract = {
  name: 'report',
  displayName: 'Report Agent',
  description: 'Builds structured briefing artifacts such as case summaries, station reports, and supervisor-ready notes.',
  responsibilities: ['report_generation', 'case_summary'],
  input: {
    description: 'Accepts entity-bound reporting requests with defined report type and audience intent.',
    requiredFields: ['query', 'entityType', 'entityId', 'reportType'],
    optionalFields: ['language'],
    acceptsCaseContext: true,
    acceptsConversationContext: true,
    acceptsStructuredEntities: true,
    acceptsUserQuery: true,
    shape: {},
  },
  output: {
    description: 'Produces structured report sections and executive summaries suitable for downstream export.',
    primaryPayload: 'report document',
    includesEvidence: true,
    includesConfidence: false,
    includesWarnings: true,
    includesHumanReviewFlag: true,
    shape: {},
  },
  tools: ['generateSummary', 'generateTimeline', 'searchAnalytics', 'translate'],
  memory: {
    scope: 'request',
    description: 'Report generation is request-scoped to preserve determinism and auditability.',
    retainedFields: ['entityType', 'entityId', 'reportType'],
    ttlSeconds: 600,
  },
  prompt: {
    mode: 'required',
    promptKey: 'report.agent.system',
    promptVersionRequired: true,
    allowRuntimeOverride: false,
    notes: ['Report formatting should remain structured and evidence-backed.'],
  },
  failureHandling: {
    mode: 'degrade_gracefully',
    retryableErrorCodes: ['AI_TOOL_TIMEOUT', 'AI_PROVIDER_TIMEOUT'],
    fallbackActions: ['return_partial_sections', 'mark_missing_sections'],
    escalateToHumanReview: true,
    suppressUnsupportedClaims: true,
  },
  confidence: {
    mode: 'optional',
    requiresSourceAttribution: true,
    requiresScoreBreakdown: false,
    downgradeOnMissingEvidence: true,
  },
  evidence: {
    mode: 'required',
    minimumCitationCount: 1,
    requireStructuredSources: true,
    requireConflictingEvidenceWarnings: true,
    allowedSourceTypes: ['CASE', 'TIMELINE_EVENT', 'ANALYTICS', 'REPORTING_SOURCE'],
  },
};

export const supervisorAgentContract: SupervisorAgentContract = {
  name: 'supervisor',
  displayName: 'Supervisor Agent',
  description: 'Supports SP/DSP/DGP-style oversight with workload signals, high-risk attention items, and delayed-case review.',
  responsibilities: ['supervisor_review', 'crime_trend_analysis', 'recommendation_generation'],
  input: {
    description: 'Accepts district, unit, officer, or case-oriented supervisory review requests.',
    requiredFields: ['query'],
    optionalFields: ['districtId', 'unitId', 'officerId', 'caseMasterId', 'requestedView'],
    acceptsCaseContext: true,
    acceptsConversationContext: true,
    acceptsStructuredEntities: true,
    acceptsUserQuery: true,
    shape: {},
  },
  output: {
    description: 'Produces attention items, workload concerns, risk flags, and recommended supervisory actions.',
    primaryPayload: 'supervisory review insights',
    includesEvidence: true,
    includesConfidence: true,
    includesWarnings: true,
    includesHumanReviewFlag: false,
    shape: {},
  },
  tools: ['searchAnalytics', 'searchRecommendations', 'searchCase', 'generateSummary'],
  memory: {
    scope: 'session',
    description: 'Retains current supervisory dashboard context and filter selections.',
    retainedFields: ['districtId', 'unitId', 'officerId', 'requestedView', 'activePriorityFilters'],
    ttlSeconds: 1800,
  },
  prompt: {
    mode: 'required',
    promptKey: 'supervisor.agent.system',
    promptVersionRequired: true,
    allowRuntimeOverride: false,
    notes: ['This agent is intended for supervisory roles and must preserve accountability context.'],
  },
  failureHandling: {
    mode: 'degrade_gracefully',
    retryableErrorCodes: ['AI_TOOL_TIMEOUT'],
    fallbackActions: ['return_verified_attention_items', 'mark_incomplete_supervisory_view'],
    escalateToHumanReview: false,
    suppressUnsupportedClaims: true,
  },
  confidence: {
    mode: 'derived',
    minimumEvidenceCount: 1,
    requiresSourceAttribution: true,
    requiresScoreBreakdown: true,
    downgradeOnMissingEvidence: true,
  },
  evidence: {
    mode: 'required',
    minimumCitationCount: 1,
    requireStructuredSources: true,
    requireConflictingEvidenceWarnings: true,
    allowedSourceTypes: ['CASE', 'ANALYTICS', 'RECOMMENDATION', 'SUPERVISORY_SIGNAL'],
  },
};

export const AI_AGENT_CONTRACTS = {
  investigation: investigationAgentContract,
  legal: legalAgentContract,
  analytics: analyticsAgentContract,
  graph: graphAgentContract,
  recommendation: recommendationAgentContract,
  report: reportAgentContract,
  supervisor: supervisorAgentContract,
} as const;

export const AI_AGENT_DEFAULT_ACCESS = {
  investigation: {
    roles: [ROLES.SUPER_ADMIN, ROLES.DGP, ROLES.IG, ROLES.SP, ROLES.DSP, ROLES.INSPECTOR, ROLES.SI, ROLES.CRIME_ANALYST],
    permissions: [PERMISSIONS.AI_USE],
  },
  legal: {
    roles: [ROLES.SUPER_ADMIN, ROLES.DGP, ROLES.IG, ROLES.SP, ROLES.DSP, ROLES.INSPECTOR, ROLES.SI, ROLES.CRIME_ANALYST],
    permissions: [PERMISSIONS.AI_USE],
  },
  analytics: {
    roles: [ROLES.SUPER_ADMIN, ROLES.DGP, ROLES.IG, ROLES.SP, ROLES.DSP, ROLES.INSPECTOR, ROLES.CRIME_ANALYST, ROLES.POLICY_MAKER],
    permissions: [PERMISSIONS.ANALYTICS_READ],
  },
  graph: {
    roles: [ROLES.SUPER_ADMIN, ROLES.DGP, ROLES.IG, ROLES.SP, ROLES.DSP, ROLES.INSPECTOR, ROLES.SI, ROLES.CRIME_ANALYST],
    permissions: [PERMISSIONS.AI_USE],
  },
  recommendation: {
    roles: [ROLES.SUPER_ADMIN, ROLES.DGP, ROLES.IG, ROLES.SP, ROLES.DSP, ROLES.INSPECTOR, ROLES.SI, ROLES.CRIME_ANALYST],
    permissions: [PERMISSIONS.AI_USE],
  },
  report: {
    roles: [ROLES.SUPER_ADMIN, ROLES.DGP, ROLES.IG, ROLES.SP, ROLES.DSP, ROLES.INSPECTOR, ROLES.SI, ROLES.CRIME_ANALYST, ROLES.POLICY_MAKER],
    permissions: [PERMISSIONS.AI_USE],
  },
  supervisor: {
    roles: [ROLES.SUPER_ADMIN, ROLES.DGP, ROLES.IG, ROLES.SP, ROLES.DSP],
    permissions: [PERMISSIONS.AI_USE, PERMISSIONS.ANALYTICS_READ],
  },
} as const;
