import React, { createContext, useContext, useState, useEffect } from 'react';

const InvestigationStateContext = createContext();

export const useInvestigation = () => {
  const context = useContext(InvestigationStateContext);
  if (!context) {
    throw new Error('useInvestigation must be used within an InvestigationStateProvider');
  }
  return context;
};

export const InvestigationStateProvider = ({ children }) => {
  // Context state for the current investigation
  const [currentContext, setCurrentContext] = useState(null); // e.g. { type: 'FIR', id: 'FIR-2026-089', officer: 'DCP Rathore' }
  const [evidenceCount, setEvidenceCount] = useState(0);
  const [peopleCount, setPeopleCount] = useState(0);
  const [vehiclesCount, setVehiclesCount] = useState(0);
  const [timelineUpdated, setTimelineUpdated] = useState('Never');
  const [confidence, setConfidence] = useState(0);

  // The artifacts generated by the AI
  const [artifacts, setArtifacts] = useState({
    timeline: [],
    evidence: [],
    people: [],
    vehicles: [],
    graph: null,
    financial: [],
    recommendations: [],
    reports: []
  });

  // Conversation memory
  const [messages, setMessages] = useState([]);
  
  // Investigation status
  const [status, setStatus] = useState('idle'); // 'idle', 'thinking', 'complete'
  const [activeAgents, setActiveAgents] = useState([]); // Array of strings like "Legal Agent: Checking IPC"
  
  // Tab state for the workspace
  const [activeTab, setActiveTab] = useState('Overview');

  const setInvestigationContext = (newContext) => {
    setCurrentContext(newContext);
  };

  const addArtifact = (type, data) => {
    setArtifacts(prev => ({
      ...prev,
      [type]: Array.isArray(prev[type]) ? [...prev[type], data] : data
    }));
  };

  const clearInvestigation = () => {
    setCurrentContext(null);
    setArtifacts({
      timeline: [], evidence: [], people: [], vehicles: [], graph: null, financial: [], recommendations: [], reports: []
    });
    setMessages([]);
    setEvidenceCount(0);
    setPeopleCount(0);
    setVehiclesCount(0);
    setConfidence(0);
    setStatus('idle');
    setActiveTab('Overview');
  };

  const value = {
    currentContext,
    setInvestigationContext,
    evidenceCount, setEvidenceCount,
    peopleCount, setPeopleCount,
    vehiclesCount, setVehiclesCount,
    timelineUpdated, setTimelineUpdated,
    confidence, setConfidence,
    artifacts,
    setArtifacts,
    addArtifact,
    messages,
    setMessages,
    status,
    setStatus,
    activeAgents,
    setActiveAgents,
    activeTab,
    setActiveTab,
    clearInvestigation
  };

  return (
    <InvestigationStateContext.Provider value={value}>
      {children}
    </InvestigationStateContext.Provider>
  );
};
