import { ROLES, type Role } from './roles';

export const PERMISSIONS = {
  USERS_MANAGE: 'users:manage',
  AUTH_AUDIT_READ: 'auth:audit:read',
  CASES_READ_ALL: 'cases:read:all',
  CASES_READ_DISTRICT: 'cases:read:district',
  CASES_READ_UNIT: 'cases:read:unit',
  CASES_WRITE: 'cases:write',
  ANALYTICS_READ: 'analytics:read',
  POLICY_READ: 'policy:read',
  AI_USE: 'ai:use',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Readonly<Record<Role, readonly Permission[]>> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.DGP]: [
    PERMISSIONS.CASES_READ_ALL,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.POLICY_READ,
    PERMISSIONS.AUTH_AUDIT_READ,
    PERMISSIONS.AI_USE,
  ],
  [ROLES.IG]: [
    PERMISSIONS.CASES_READ_ALL,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.AUTH_AUDIT_READ,
    PERMISSIONS.AI_USE,
  ],
  [ROLES.SP]: [
    PERMISSIONS.CASES_READ_DISTRICT,
    PERMISSIONS.CASES_WRITE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.AI_USE,
  ],
  [ROLES.DSP]: [
    PERMISSIONS.CASES_READ_DISTRICT,
    PERMISSIONS.CASES_WRITE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.AI_USE,
  ],
  [ROLES.INSPECTOR]: [
    PERMISSIONS.CASES_READ_UNIT,
    PERMISSIONS.CASES_WRITE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.AI_USE,
  ],
  [ROLES.SI]: [PERMISSIONS.CASES_READ_UNIT, PERMISSIONS.CASES_WRITE, PERMISSIONS.AI_USE],
  [ROLES.CONSTABLE]: [PERMISSIONS.CASES_READ_UNIT],
  [ROLES.CRIME_ANALYST]: [
    PERMISSIONS.CASES_READ_DISTRICT,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.AI_USE,
  ],
  [ROLES.POLICY_MAKER]: [PERMISSIONS.ANALYTICS_READ, PERMISSIONS.POLICY_READ],
};

export function permissionsForRole(role: Role): Permission[] {
  return [...ROLE_PERMISSIONS[role]];
}
