import type { AiWorkflowNodeName } from './langgraph.types';

export interface AiWorkflowNodeDefinition {
  name: AiWorkflowNodeName;
  description: string;
  category: 'entry' | 'analysis' | 'governance' | 'execution' | 'post_processing' | 'terminal';
  requiredInputs: readonly string[];
  producedOutputs: readonly string[];
  canRetry: boolean;
  canTriggerHumanReview: boolean;
}

export const AI_WORKFLOW_NODES: readonly AiWorkflowNodeDefinition[] = [
  {
    name: 'START',
    description: 'Entry node that initializes workflow state and trace metadata.',
    category: 'entry',
    requiredInputs: ['request'],
    producedOutputs: ['sharedContext', 'visitedNodes'],
    canRetry: false,
    canTriggerHumanReview: false,
  },
  {
    name: 'intent_detection',
    description: 'Classifies the user request into an investigation intent for downstream routing.',
    category: 'analysis',
    requiredInputs: ['query', 'sharedContext'],
    producedOutputs: ['detectedIntent'],
    canRetry: true,
    canTriggerHumanReview: true,
  },
  {
    name: 'entity_extraction',
    description: 'Extracts structured people, case, location, legal, and temporal entities from the request.',
    category: 'analysis',
    requiredInputs: ['query', 'detectedIntent'],
    producedOutputs: ['extractedEntities'],
    canRetry: true,
    canTriggerHumanReview: true,
  },
  {
    name: 'permission_check',
    description: 'Verifies AI access, role scope, and jurisdiction boundaries before execution.',
    category: 'governance',
    requiredInputs: ['sharedContext', 'detectedIntent'],
    producedOutputs: ['permissionsValidated'],
    canRetry: false,
    canTriggerHumanReview: false,
  },
  {
    name: 'task_planner',
    description: 'Builds the cross-agent execution plan and determines whether human review may be required.',
    category: 'analysis',
    requiredInputs: ['detectedIntent', 'extractedEntities', 'permissionsValidated'],
    producedOutputs: ['taskPlan', 'executionBatches'],
    canRetry: true,
    canTriggerHumanReview: true,
  },
  {
    name: 'agent_router',
    description: 'Selects primary and supporting agents and maps them into execution batches.',
    category: 'analysis',
    requiredInputs: ['taskPlan'],
    producedOutputs: ['executionBatches'],
    canRetry: true,
    canTriggerHumanReview: false,
  },
  {
    name: 'parallel_agent_execution',
    description: 'Runs routed agents according to the execution plan using parallel or hybrid coordination.',
    category: 'execution',
    requiredInputs: ['executionBatches'],
    producedOutputs: ['agentOutputs'],
    canRetry: true,
    canTriggerHumanReview: true,
  },
  {
    name: 'evidence_aggregator',
    description: 'Merges facts, citations, and warnings from agent outputs into a normalized evidence bundle.',
    category: 'post_processing',
    requiredInputs: ['agentOutputs'],
    producedOutputs: ['evidenceBundle'],
    canRetry: true,
    canTriggerHumanReview: true,
  },
  {
    name: 'confidence_calculator',
    description: 'Computes reliability signals based on evidence quality, coverage, and consistency.',
    category: 'post_processing',
    requiredInputs: ['evidenceBundle', 'agentOutputs'],
    producedOutputs: ['confidenceBreakdown'],
    canRetry: true,
    canTriggerHumanReview: true,
  },
  {
    name: 'explainability',
    description: 'Builds transparent reasoning artifacts, agent contribution summaries, and citation traces.',
    category: 'post_processing',
    requiredInputs: ['evidenceBundle', 'confidenceBreakdown'],
    producedOutputs: ['explainability'],
    canRetry: true,
    canTriggerHumanReview: true,
  },
  {
    name: 'response_generator',
    description: 'Assembles the final evidence-backed response payload for the caller.',
    category: 'post_processing',
    requiredInputs: ['evidenceBundle', 'confidenceBreakdown', 'explainability'],
    producedOutputs: ['response'],
    canRetry: true,
    canTriggerHumanReview: true,
  },
  {
    name: 'human_review_gate',
    description: 'Determines whether the workflow must pause for supervisor or legal review.',
    category: 'governance',
    requiredInputs: ['response', 'confidenceBreakdown'],
    producedOutputs: ['humanReview'],
    canRetry: false,
    canTriggerHumanReview: true,
  },
  {
    name: 'human_review_queue',
    description: 'Creates a review task and routes the case to the appropriate human reviewer queue.',
    category: 'governance',
    requiredInputs: ['humanReview'],
    producedOutputs: ['humanReview'],
    canRetry: true,
    canTriggerHumanReview: false,
  },
  {
    name: 'human_review_resolution',
    description: 'Captures reviewer disposition and merges it back into workflow state.',
    category: 'governance',
    requiredInputs: ['humanReview'],
    producedOutputs: ['response', 'humanReview'],
    canRetry: false,
    canTriggerHumanReview: false,
  },
  {
    name: 'audit_logger',
    description: 'Persists the workflow timeline, decisions, warnings, and review status for traceability.',
    category: 'governance',
    requiredInputs: ['response', 'auditTrail'],
    producedOutputs: ['auditTrail'],
    canRetry: true,
    canTriggerHumanReview: false,
  },
  {
    name: 'END',
    description: 'Marks successful workflow completion and returns the final response contract.',
    category: 'terminal',
    requiredInputs: ['response'],
    producedOutputs: ['terminalStatus'],
    canRetry: false,
    canTriggerHumanReview: false,
  },
  {
    name: 'FAILED',
    description: 'Marks terminal workflow failure when recovery is not possible.',
    category: 'terminal',
    requiredInputs: ['failureReason'],
    producedOutputs: ['terminalStatus'],
    canRetry: false,
    canTriggerHumanReview: false,
  },
] as const;
